export class Const {
    static DateFormat = {
        isoWithoutZ: 'YYYY-MM-DDTHH:mm:ss',
    }
}

export enum AccessControls {

    // User
    USER_READ_LIST = 'USER_READ_LIST',
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_DELETE = 'USER_DELETE',
    USER_READ_DETAILS = 'USER_READ_DETAILS',

    //Customer
    CUSTOMER_READ_LIST = 'CUSTOMER_READ_LIST',
    CUSTOMER_CREATE = 'CUSTOMER_CREATE',
    CUSTOMER_UPDATE = 'CUSTOMER_UPDATE',
    CUSTOMER_DELETE = 'CUSTOMER_DELETE',
    CUSTOMER_READ_DETAILS = 'CUSTOMER_READ_DETAILS',

    //Invoice
    INVOICE_READ_LIST = 'INVOICE_READ_LIST',
    INVOICE_CREATE = 'INVOICE_CREATE',
    INVOICE_UPDATE = 'INVOICE_UPDATE',
    INVOICE_DELETE = 'INVOICE_DELETE',
    INVOICE_READ_DETAILS = 'INVOICE_READ_DETAILS',
    INVOICE_PRINT = 'INVOICE_PRINT',

    //Shop
    SHOP_READ_LIST = 'SHOP_READ_LIST',
    SHOP_CREATE = 'SHOP_CREATE',
    SHOP_UPDATE = 'SHOP_UPDATE',
    SHOP_DELETE = 'SHOP_DELETE',
    SHOP_READ_DETAILS = 'SHOP_READ_DETAILS',

    // Log Report
    LOG_READ_ALL = 'LOG_READ_ALL',

    // Dashboard
    DASHBOARD_VIEW = 'DASHBOARD_VIEW',
}
